
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NavbarContextProvider } from "@/app/context/NavbarContext";
import { LanguageProvider } from "@/app/context/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <NavbarContextProvider>
            <Navbar />
            <div className="max-w-[1200px] mx-auto flex justify-center items-center">
            {children}
            </div>
            <Footer />
          </NavbarContextProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
